/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package bot

import bot.core.CommandHandler
import bot.core.TriggerRegistrator
import dev.kord.core.Kord
import dev.kord.core.event.message.MessageCreateEvent
import dev.kord.core.kordLogger
import dev.kord.core.on
import dev.kord.gateway.Intent
import dev.kord.gateway.PrivilegedIntent

private lateinit var kordInstance: Kord

suspend fun main(vararg args: String) {

    kordInstance = Kord(token = args.firstOrNull() ?: error("token required"))

    kordInstance.on<MessageCreateEvent> {
        if (message.author?.isBot == true) return@on
        val content = this.message.content
        kordLogger.info("Incoming message \"${content}\"")
        if (content.startsWith("!gnome")) {
            CommandHandler.handle(
                event = this,
                args = content
                    .split(" ")
                    .drop(1)
            )
        }
    }

    TriggerRegistrator.registerTriggers()

    kordInstance.login {
        // we need to specify this to receive the content of messages
        @OptIn(PrivilegedIntent::class)
        intents += Intent.MessageContent
    }
}

fun getKordInstance() = kordInstance