/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/8.1.1/userguide/building_java_projects.html
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    id("org.jetbrains.kotlin.jvm") version "1.8.10"

    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
    jcenter()

}

dependencies {
//    testImplementation("org.jetbrains.kotlin:kotlin-test-junit5")
//    testImplementation("org.junit.jupiter:junit-jupiter-engine:5.9.1")

    implementation(kotlin("reflect"))
    // Discord
//    implementation("dev.kord:kord-core:0.9.0")
//    implementation("dev.kord:kord-voice:0.9.0")
    implementation("dev.kord:kord-core-voice:0.9.0")

    // Dependency Injection
    implementation("com.google.inject:guice:7.0.0")

    implementation("org.slf4j:slf4j-simple:2.0.3")

    // Audio player
    implementation("com.sedmelluq:lavaplayer:1.3.73")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(11))
    }
}

application {
    // Define the main class for the application.
    mainClass.set("bot.AppKt")
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
