steps:
  - name: gcr.io/kaniko-project/executor:latest
    args:
      - --destination=gcr.io/$PROJECT_ID/gnome
      - --cache=true
      - --cache-ttl=1h
      - --build-arg=DISCORD_AUTH_TOKEN
      - --build-arg=HUGGING_FACE_AUTH_TOKEN
      - --build-arg=CUSTOM_ENTRY_CONFIG_BASE64
    env:
      - 'DISCORD_AUTH_TOKEN=$_DISCORD_AUTH_TOKEN'
      - 'HUGGING_FACE_AUTH_TOKEN=$_HUGGING_FACE_AUTH_TOKEN'
      - 'CUSTOM_ENTRY_CONFIG_BASE64=_CUSTOM_ENTRY_CONFIG_BASE64'
  - name: gcr.io/cloud-builders/gcloud
    args: [ compute, instance-groups, managed, rolling-action, restart, gnome-docker, --zone=us-central1-a ]