steps:
  - name: gcr.io/kaniko-project/executor:latest
    args:
      - --destination=gcr.io/$PROJECT_ID/gnome
      - --cache=true
      - --cache-ttl=1h
      - --env DISCORD_AUTH_TOKEN=$_DISCORD_AUTH_TOKEN
  - name: gcr.io/cloud-builders/gcloud
    args: [ compute, instance-groups, managed, rolling-action, restart, gnome-docker, --zone=us-central1-a ]