package bot.constants

val GNOME_COMMAND_PREFIXES = listOf("!gnome", "!g")
const val DISCORD_TOKEN_ENV_VAR = "DISCORD_AUTH_TOKEN"
const val HUGGING_FACE_TOKEN_ENV_VAR = "HUGGING_FACE_AUTH_TOKEN"
const val CUSTOM_ENTRY_ENV_VAR = "CUSTOM_ENTRY_CONFIG_BASE64"
