{
  "formatVersion": "1.1",
  "component": {
    "group": "com.sedmelluq",
    "module": "lavaplayer",
    "version": "1.3.77",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.2",
      "buildId": "jnhx54aw2nay3exq26mh3tngga"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.sedmelluq",
          "module": "lava-common",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpclient",
          "version": {
            "requires": "4.5.10"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "lavaplayer-1.3.77.jar",
          "url": "lavaplayer-1.3.77.jar",
          "size": 706090,
          "sha512": "6888dbab36e060bfc801bce99915faefcb3aaa7a1bbedb1d29852c207705b78384ae909d4361bf5fc4b87a979015ac0f42d3116eec5dd48cc440d12d46341c08",
          "sha256": "f1b32ecd2a4f46680df301f526776fdadfd7bad3cbd113f16fc6e076bdf33d84",
          "sha1": "89401c843d79108a69319bfc2e9e043335165ce5",
          "md5": "64add424e8b13ba096af604ecda4b03b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.sedmelluq",
          "module": "lavaplayer-natives",
          "version": {
            "requires": "1.3.14"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.25"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "net.iharder",
          "module": "base64",
          "version": {
            "requires": "2.3.9"
          }
        },
        {
          "group": "com.sedmelluq",
          "module": "lava-common",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpclient",
          "version": {
            "requires": "4.5.10"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "lavaplayer-1.3.77.jar",
          "url": "lavaplayer-1.3.77.jar",
          "size": 706090,
          "sha512": "6888dbab36e060bfc801bce99915faefcb3aaa7a1bbedb1d29852c207705b78384ae909d4361bf5fc4b87a979015ac0f42d3116eec5dd48cc440d12d46341c08",
          "sha256": "f1b32ecd2a4f46680df301f526776fdadfd7bad3cbd113f16fc6e076bdf33d84",
          "sha1": "89401c843d79108a69319bfc2e9e043335165ce5",
          "md5": "64add424e8b13ba096af604ecda4b03b"
        }
      ]
    }
  ]
}
